databases:
  - name: invoices
    databaseName: invoices_t9ym
    user: invoices_t9ym_user

services:
  - type: web
    name: invoices
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: invoices
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false